apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: edge-service

resources:
  - deployment.yml
  - ingress.yml
  - service.yml

configMapGenerator:
  - name: edge-service
    files:
      - application.yml
